name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 UTC 执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库 B
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 添加上游（Upstream）仓库
        run: |
          git remote add upstream https://github.com/mannaandpoem/OpenManus.git
          git fetch upstream
      
      - name: 合并上游分支
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
